#!/bin/bash

mkdir checkpoints
mkdir log

DATETIME="`date '+%Y%m%d-%H%M%S'`"

STDERRLOG="log/${DATETIME}stderr.log"
STDOUTLOG="log/${DATETIME}stdout.log"


/home/USERNAME/.conda/envs/horovod/bin/mpirun --allow-run-as-root --tag-output -np 3 -H 192.168.15.161:1,192.168.15.162:1,192.168.15.163:1 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib -mca plm_rsh_args "-p 22" -mca btl_tcp_if_include eth0 -x NCCL_SOCKET_IFNAME=eth0  -x CONDA_SHLVL -x LD_LIBRARY_PATH -x LS_COLORS -x CONDA_EXE -x LC_MEASUREMENT -x SSH_CONNECTION -x LESSCLOSE -x GPROF -x LC_PAPER -x LC_MONETARY -x LANG -x GXX -x LD_GOLD -x DEBUG_CPPFLAGS -x DEBUG_CFLAGS -x GCC_NM -x CONDA_PREFIX -x GCC_RANLIB -x CFLAGS -x GCC_AR -x _CE_M -x CC -x READELF -x LC_NAME -x XDG_SESSION_ID -x USER -x CXXFLAGS -x CONDA_PREFIX_1 -x STRIP -x OBJCOPY -x _CONDA_PYTHON_SYSCONFIGDATA_NAME -x QT_QPA_PLATFORMTHEME -x PWD -x HOME -x ADDR2LINE -x CONDA_PYTHON_EXE -x HOST -x SSH_CLIENT -x XDG_DATA_DIRS -x RANLIB -x OBJDUMP -x AS -x AR -x CONDA_BACKUP_HOST -x _CE_CONDA -x LC_ADDRESS -x LC_NUMERIC -x NM -x CONDA_PROMPT_MODIFIER -x SSH_TTY -x MAIL -x DEBUG_CXXFLAGS -x CXX -x TERM -x SHELL -x CXXFILT -x HOROVOD_TIMELINE=/home/USERNAME/future-internet-architecture/log/${DATETIME}timeline.json -x HOROVOD_TIMELINE_MARK_CYCLES=0 -x ELFEDIT -x SHLVL -x CPPFLAGS -x LC_TELEPHONE -x STRINGS -x LOGNAME -x DBUS_SESSION_BUS_ADDRESS -x XDG_RUNTIME_DIR -x LDFLAGS -x PATH -x LC_IDENTIFICATION -x GCC -x CONDA_DEFAULT_ENV -x SIZE -x CPP -x LD -x LESSOPEN -x LC_TIME -x _ -x HOROVOD_STALL_CHECK_TIME_SECONDS -x HOROVOD_STALL_SHUTDOWN_TIME_SECONDS -x HOROVOD_NUM_NCCL_STREAMS -x HOROVOD_MLSL_BGT_AFFINITY -x HOROVOD_GLOO_TIMEOUT_SECONDS python train-with-logging.py > >(tee $STDOUTLOG) 2> >(tee $STDERRLOG >&2)

